CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [email] VARCHAR(255) NOT NULL, 
    [name ] VARCHAR(255) NOT NULL, 
    [skype] VARCHAR(255) NOT NULL, 
    [phone] VARCHAR(50) NOT NULL, 
    [linkedin] VARCHAR(255) NULL, 
    [city] VARCHAR(255) NOT NULL, 
    [state] VARCHAR(255) NOT NULL, 
    [availability] VARCHAR(100) NOT NULL, 
    [bestTimeTowork] VARCHAR(100) NOT NULL, 
    [hourlySalary] SMALLINT NOT NULL, 
    [bankYourName] VARCHAR(255) NULL, 
    [bankName] VARCHAR(255) NULL, 
    [bankAgency] VARCHAR(20) NULL, 
    [bankAccountType] VARCHAR(20) NULL, 
    [bankAccountNumber] VARCHAR(20) NULL, 
    [ionic] TINYINT NOT NULL DEFAULT 0, 
    [iso] TINYINT NOT NULL DEFAULT 0, 
    [html] TINYINT NOT NULL DEFAULT 0, 
    [css] TINYINT NOT NULL DEFAULT 0, 
    [bootstrap] TINYINT NOT NULL DEFAULT 0, 
    [jquery] TINYINT NOT NULL DEFAULT 0, 
    [angularJs] TINYINT NOT NULL DEFAULT 0, 
    [java] TINYINT NOT NULL DEFAULT 0, 
    [aspnetMVC] TINYINT NOT NULL DEFAULT 0, 
    [languageC] TINYINT NOT NULL DEFAULT 0, 
    [languageCPlusPlus] TINYINT NOT NULL DEFAULT 0, 
    [cake] TINYINT NOT NULL DEFAULT 0, 
    [django] TINYINT NOT NULL DEFAULT 0, 
    [majento] TINYINT NOT NULL DEFAULT 0, 
    [PHP] TINYINT NOT NULL DEFAULT 0, 
    [vue] TINYINT NOT NULL DEFAULT 0, 
    [wordperss] TINYINT NOT NULL DEFAULT 0, 
    [python] TINYINT NOT NULL DEFAULT 0, 
    [ruby] TINYINT NOT NULL DEFAULT 0, 
    [sqlServer] TINYINT NOT NULL DEFAULT 0, 
    [mysql] TINYINT NOT NULL DEFAULT 0, 
    [salesforce] TINYINT NOT NULL DEFAULT 0, 
    [photophop] TINYINT NOT NULL DEFAULT 0, 
    [illustrator] TINYINT NOT NULL DEFAULT 0, 
    [seo] TINYINT NOT NULL DEFAULT 0, 
    [others] TEXT NOT NULL DEFAULT 0, 
    [crudLink] TEXT NULL , 
    [portifolio] TEXT NULL
)
