//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTalents.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class talent
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "O email deve ser informado!")]
        public string email { get; set; }
        [Required]
        public string name_ { get; set; }
        [Required]
        public string skype { get; set; }
        [Required]
        public string phone { get; set; }
        public string linkedin { get; set; }
        [Required]
        public string city { get; set; }
        [Required]
        public string state { get; set; }
        public string portifolio { get; set; }
        [Required]
        public int id_availability { get; set; }
        [Required]
        public int id_besttime { get; set; }
        [Required]
        public short hourlySalary { get; set; }
        public string bankYourName { get; set; }
        public string bankName { get; set; }
        public string bankCPF { get; set; }
        public string bankAgency { get; set; }
        public string bankAccountType { get; set; }
        public string bankAccountNumber { get; set; }
        [Required]
        public byte ionic { get; set; }
        [Required]
        public byte android { get; set; }
        [Required]
        public byte ios { get; set; }
        [Required]
        public byte html { get; set; }
        [Required]
        public byte css { get; set; }
        [Required]
        public byte bootstrap { get; set; }
        [Required]
        public byte jquery { get; set; }
        [Required]
        public byte angularJs { get; set; }
        [Required]
        public byte java { get; set; }
        [Required]
        public byte aspnetMVC { get; set; }
        [Required]
        public byte languageC { get; set; }
        [Required]
        public byte languageCPlusPlus { get; set; }
        [Required]
        public byte cake { get; set; }
        [Required]
        public byte django { get; set; }
        [Required]
        public byte majento { get; set; }
        [Required]
        public byte PHP { get; set; }
        [Required]
        public byte vue { get; set; }
        [Required]
        public byte wordperss { get; set; }
        [Required]
        public byte python { get; set; }
        [Required]
        public byte ruby { get; set; }
        [Required]
        public byte sqlServer { get; set; }
        [Required]
        public byte mysql { get; set; }
        [Required]
        public byte salesforce { get; set; }
        [Required]
        public byte photophop { get; set; }
        [Required]
        public byte illustrator { get; set; }
        [Required]
        public byte seo { get; set; }
        public string others { get; set; }
        public string crudLink { get; set; }
    
        public virtual availability availability { get; set; }
        public virtual besttime besttime { get; set; }
    }
}
